name: Build frontend

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone ChatGPT-Proxy-V4
        run: git clone https://github.com/moeakwak/ChatGPT-Proxy-V4.git

      # - name: Setup Go
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: "1.20"
      #     cache-dependency-path: ChatGPT-Proxy-V4/go.sum

      # - name: build ChatGPT-Proxy-V4
      #   run: |
      #     cd ChatGPT-Proxy-V4
      #     go build

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies in frontend
        run: |
          cd frontend
          pnpm install
      - name: build frontend
        run: |
          cd frontend
          pnpm build
